### ISSUE TITLE
RangeError: "size" argument must not be negative

### ISSUE THREAD

**Issue by HACKHERS** [FormidableLabs/nodejs-dashboard#73]
Just installed nodejs-dashboard globally, but I'm getting error.

Command: `nodejs-dashboard -- node -r nodejs-dashboard index.js`

Error code:
```
RangeError: "size" argument must not be negative
    at Function.Buffer.alloc (buffer.js:229:3)
    at new Buffer (buffer.js:152:19)
    at new Canvas (C:\Users\User\AppData\Roaming\npm\node_modules\nodejs-dashboard\node_modules\drawille-blessed-contrib\index.js:17:18)
    at new Context (C:\Users\User\AppData\Roaming\npm\node_modules\nodejs-dashboard\node_modules\drawille-canvas-blessed-contrib\index.js:11:18)
    at module.exports.Canvas.getContext (C:\Users\User\AppData\Roaming\npm\node_modules\nodejs-dashboard\node_modules\drawille-canvas-blessed-contrib\index.js:274:24)
    at Line.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\nodejs-dashboard\node_modules\blessed-contrib\lib\widget\canvas.js:22:29)
    at Line.EventEmitter._emit (C:\Users\User\AppData\Roaming\npm\node_modules\nodejs-dashboard\node_modules\blessed\lib\events.js:98:20)
    at Line.EventEmitter.emit (C:\Users\User\AppData\Roaming\npm\node_modules\nodejs-dashboard\node_modules\blessed\lib\events.js:117:12)
    at emit (C:\Users\User\AppData\Roaming\npm\node_modules\nodejs-dashboard\node_modules\blessed\lib\widgets\node.js:109:15)
    at Box.Node.insert (C:\Users\User\AppData\Roaming\npm\node_modules\nodejs-dashboard\node_modules\blessed\lib\widgets\node.js:111:5)
```

**Comment by ryan-roemer** [comment]
Hi @HACKHERS ! 

Can you create a minimal repository that exposes the error and then give us install + error reproduction steps so that we can more quickly diagnose what's going on? Thanks!

**Comment by ryan-roemer** [comment]
Closing due to lack of activity / a reproduction. If this issue persists in latest package, please create a new issue / reopen a minimal repository that exposes the error. Thanks!

**Comment by alfianriv** [comment]
I have same issues here

**Comment by ryan-roemer** [comment]
Hi @alfianriv -- same request to help us hone in and identify the problem:

Can you create a minimal repository that exposes the error and then give us install + error reproduction steps so that we can more quickly diagnose what's going on? Thanks!
