### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by hooper-hc** [FormidableLabs/nodejs-dashboard#92]
RangeError [ERR_INVALID_OPT_VALUE]: The value "-63" is invalid for option "size"

**Comment by crobinson42** [comment]
I'm getting the same issue, any ideas?

```
 LANG=en_US.UTF-8 TERM=xterm-256color nodejs-dashboard -- node -r nodejs-dashboard                                                                     1 ↵  10363  12:02:46 
Waiting for client connection on 9838...
RangeError [ERR_INVALID_OPT_VALUE]: The value "-61" is invalid for option "size"
    at Function.alloc (buffer.js:279:3)
    at new Buffer (buffer.js:181:19)

````

**Comment by huypvw** [comment]
Same
```
Waiting for client connection on 9838...
RangeError [ERR_INVALID_OPT_VALUE]: The value "-60" is invalid for option "size"
```

**Comment by ryan-roemer** [comment]
If someone could create a minimal repository with:

1. install
2. command that produces the error

steps then we could pull it down and hopefully diagnose it.

Thanks!
